default: &default
  addapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: PioneerSpace_production
  username: root

development:
  <<: *default
  database: PioneerSpace_development
test:
  <<: *default
  database: PioneerSpace_test
